[package]
name = "matchbook-types"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty_assertions = "0.6.1"
quickcheck = "1.0.3"

[dependencies]
serde = {version="1.0", features=["derive"]}
